### ISSUE TITLE
twilio-chat.min.js:171 Uncaught (in promise) t: Transport failure: UNKNOWN_ACTIVE_PRODUCT (status: 0, code: 0)

### ISSUE THREAD

**Issue by Waqas-Sharif** [TwilioDevEd/twiliochat-laravel#116]
When I integrated your given code in my laravel project that error occoured:

twilio-chat.min.js:171 Uncaught (in promise) t: Transport failure: UNKNOWN_ACTIVE_PRODUCT (status: 0, code: 0)
    at t (http://media.twiliocdn.com/sdk/js/chat/v4.0/twilio-chat.min.js:171:160496)
    at new t (http://media.twiliocdn.com/sdk/js/chat/v4.0/twilio-chat.min.js:171:160313)
    at m (http://media.twiliocdn.com/sdk/js/chat/v4.0/twilio-chat.min.js:171:90942)
    at http://media.twiliocdn.com/sdk/js/chat/v4.0/twilio-chat.min.js:171:91949

**Comment by Waqas-Sharif** [comment]
Is there any contributor or expert to define or fix the subject issue?..
